Fix compilation error
```
[error] /src/main/scala/URITemplate.scala:79:24: type mismatch;
[error]  found   : Unencoded.this.char.type (with underlying type Char)
[error]  required: ?{def intValue: ?}
[error] Note that implicit conversions are not applicable because they are
ambiguous:
[error]  both method charWrapper in class LowPriorityImplicits of type (c:
Char)scala.runtime.RichChar
[error]  and method int2Integer in object Predef of type (x: Int)Integer
[error]  are possible conversion functions from Unencoded.this.char.type to
?{def intValue: ?}
[error]   def expanded = "%" + char.intValue().toHexString.toUpperCase
[error]                        ^
[error] one error found
```